# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false
    cache:                  false
    etag:                   true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   true

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    #csrf_secret:            8b58df5235bc6f3217d3531b406585ba20e3a833
    
    i18n: true

    charset: UTF-8

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    default_culture:        en

    enabled_modules:        [default,sfCaptchaGD,sfDependentSelectAuto]

    standard_helpers:       [Partial, Cache, I18N, jQuery,Date,Number,General]


    error_404_module:       home
    error_404_action:       error404

    login_module:           login
    login_action:           index
 
    secure_module:          login
    secure_action:          index

    rich_text_js_dir:       js/tiny_mce

    compressed:             true 
    etag:                   true
