<?php

/**
 * BaseSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $value
 * @property enum $type
 * 
 * @method string  getName()  Returns the current record's "name" value
 * @method clob    getValue() Returns the current record's "value" value
 * @method enum    getType()  Returns the current record's "type" value
 * @method Setting setName()  Sets the current record's "name" value
 * @method Setting setValue() Sets the current record's "value" value
 * @method Setting setType()  Sets the current record's "type" value
 * 
 * @package    classifieds
 * @subpackage model
 * @author     Sandip Sathavara <sandip.sathavara@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('setting');
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 40,
             ));
        $this->hasColumn('value', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'default' => 'STRING',
             'values' => 
             array(
              0 => 'STRING',
              1 => 'INTEGER',
              2 => 'BOOLEAN',
             ),
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}