<?php

/**
 * BasePages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $slug
 * @property string $decription
 * @property boolean $status
 * @property boolean $is_default
 * 
 * @method string  getTitle()      Returns the current record's "title" value
 * @method string  getSlug()       Returns the current record's "slug" value
 * @method string  getDecription() Returns the current record's "decription" value
 * @method boolean getStatus()     Returns the current record's "status" value
 * @method boolean getIsDefault()  Returns the current record's "is_default" value
 * @method Pages   setTitle()      Sets the current record's "title" value
 * @method Pages   setSlug()       Sets the current record's "slug" value
 * @method Pages   setDecription() Sets the current record's "decription" value
 * @method Pages   setStatus()     Sets the current record's "status" value
 * @method Pages   setIsDefault()  Sets the current record's "is_default" value
 * 
 * @package    classifieds
 * @subpackage model
 * @author     Sandip Sathavara <sandip.sathavara@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pages');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('decription', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_default', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));


        $this->index('slug', array(
             'fields' => 
             array(
              0 => 'slug',
             ),
             ));
        $this->index('is_default', array(
             'fields' => 
             array(
              0 => 'is_default',
             ),
             ));
        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'decription',
             ),
             ));
        $this->actAs($i18n0);
    }
}