<?php

/**
 * BaseAds
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $page
 * @property string $position
 * @property string $ad_type
 * @property string $target_url
 * @property string $ad_data
 * @property string $banner_image
 * @property timestamp $start_dt
 * @property timestamp $end_dt
 * @property boolean $is_published
 * 
 * @method string    getName()         Returns the current record's "name" value
 * @method string    getPage()         Returns the current record's "page" value
 * @method string    getPosition()     Returns the current record's "position" value
 * @method string    getAdType()       Returns the current record's "ad_type" value
 * @method string    getTargetUrl()    Returns the current record's "target_url" value
 * @method string    getAdData()       Returns the current record's "ad_data" value
 * @method string    getBannerImage()  Returns the current record's "banner_image" value
 * @method timestamp getStartDt()      Returns the current record's "start_dt" value
 * @method timestamp getEndDt()        Returns the current record's "end_dt" value
 * @method boolean   getIsPublished()  Returns the current record's "is_published" value
 * @method Ads       setName()         Sets the current record's "name" value
 * @method Ads       setPage()         Sets the current record's "page" value
 * @method Ads       setPosition()     Sets the current record's "position" value
 * @method Ads       setAdType()       Sets the current record's "ad_type" value
 * @method Ads       setTargetUrl()    Sets the current record's "target_url" value
 * @method Ads       setAdData()       Sets the current record's "ad_data" value
 * @method Ads       setBannerImage()  Sets the current record's "banner_image" value
 * @method Ads       setStartDt()      Sets the current record's "start_dt" value
 * @method Ads       setEndDt()        Sets the current record's "end_dt" value
 * @method Ads       setIsPublished()  Sets the current record's "is_published" value
 * 
 * @package    classifieds
 * @subpackage model
 * @author     Sandip Sathavara <sandip.sathavara@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAds extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ads');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('page', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('position', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ad_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('target_url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ad_data', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('banner_image', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('start_dt', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('end_dt', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}