<?php

/**
 * BaseEmails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $from_email
 * @property string $from_name
 * @property string $subject
 * @property string $body
 * @property boolean $status
 * 
 * @method string  getTitle()      Returns the current record's "title" value
 * @method string  getFromEmail()  Returns the current record's "from_email" value
 * @method string  getFromName()   Returns the current record's "from_name" value
 * @method string  getSubject()    Returns the current record's "subject" value
 * @method string  getBody()       Returns the current record's "body" value
 * @method boolean getStatus()     Returns the current record's "status" value
 * @method Emails  setTitle()      Sets the current record's "title" value
 * @method Emails  setFromEmail()  Sets the current record's "from_email" value
 * @method Emails  setFromName()   Sets the current record's "from_name" value
 * @method Emails  setSubject()    Sets the current record's "subject" value
 * @method Emails  setBody()       Sets the current record's "body" value
 * @method Emails  setStatus()     Sets the current record's "status" value
 * 
 * @package    classifieds
 * @subpackage model
 * @author     Sandip Sathavara <sandip.sathavara@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('emails');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('from_email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('from_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'from_name',
              2 => 'subject',
              3 => 'body',
             ),
             ));
        $this->actAs($i18n0);
    }
}