<?php

/**
 * BaseStates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $country_id
 * @property string $name
 * @property boolean $is_popular
 * @property boolean $status
 * @property Countries $Countries
 * @property Doctrine_Collection $Citys
 * @property Doctrine_Collection $Posts
 * 
 * @method integer             getCountryId()  Returns the current record's "country_id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method boolean             getIsPopular()  Returns the current record's "is_popular" value
 * @method boolean             getStatus()     Returns the current record's "status" value
 * @method Countries           getCountries()  Returns the current record's "Countries" value
 * @method Doctrine_Collection getCitys()      Returns the current record's "Citys" collection
 * @method Doctrine_Collection getPosts()      Returns the current record's "Posts" collection
 * @method States              setCountryId()  Sets the current record's "country_id" value
 * @method States              setName()       Sets the current record's "name" value
 * @method States              setIsPopular()  Sets the current record's "is_popular" value
 * @method States              setStatus()     Sets the current record's "status" value
 * @method States              setCountries()  Sets the current record's "Countries" value
 * @method States              setCitys()      Sets the current record's "Citys" collection
 * @method States              setPosts()      Sets the current record's "Posts" collection
 * 
 * @package    classifieds
 * @subpackage model
 * @author     Sandip Sathavara <sandip.sathavara@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStates extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('states');
        $this->hasColumn('country_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_popular', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Countries', array(
             'local' => 'country_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Citys', array(
             'local' => 'id',
             'foreign' => 'state_id'));

        $this->hasMany('Posts', array(
             'local' => 'id',
             'foreign' => 'state_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($i18n0);
    }
}