<?php

/**
 * Pages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    classifieds
 * @subpackage model
 * @author     Sandip Sathavara <sandip.sathavara@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Pages extends BasePages
{

	 public function getSlugurl($slug='')
	 {
		return 'http://'.sfContext::getInstance()->getRequest()->getHost().'/'.$this->getSlug() ;
	 }
	 
}